### ISSUE TITLE
git clone URL in README points to wrong project

### ISSUE THREAD

**Issue by jrzerr** [Bloc/base-frontend-project#1]
The git clone URL in the README points to your own joelip github repo, which I'm assuming is the old URL before you transferred the project to Bloc's github acct.

**Comment by joelip** [comment]
@jrzerr Is this on the roadmap? Or this README?

**Comment by joelip** [comment]
And if it's the roadmap, is it all projects referencing the this repo or just one in particular?

**Comment by jrzerr** [comment]
Nope, just in the repo.  Had a student follow the directions in the repo's
README and it gave him an error so wanted to make sure it doesn't trip
anybody else in the future.

On Fri, Feb 6, 2015 at 12:01 PM, Joe Lipper <notifications@github.com>
wrote:

> And if it's the roadmap, is it all projects referencing the this repo or
> just one in particular?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Bloc/base-frontend-project/issues/1#issuecomment-73293045>
> .
>



-- 
Website <http://www.jeremyzerr.com> | LinkedIn
<http://linkedin.com/in/jrzerr> | Twitter <http://twitter.com/jrzerr> |
Google+ <https://plus.google.com/108959426484910393576>

**Comment by joelip** [comment]
Hey @jrzerr, just updated the project with: https://github.com/Bloc/base-frontend-project/pull/2

Thanks for pointing it out!
